---
# sandbox-setup.yml
#
# This is the main YAML formatted file which is done in spaces and not tabs, and whitespace.
# If you do not stick to the format, it will fail on provision.

# Important Note
#
# If you need to add a new site, copy the example and uncomment the lines and enter site
# name. You will then need to run and reprovision by using vagrant reload --provision.

# Below are your sites that gets generated when provision or when you run vagrant up for the first time.
sites:
  sandbox:
    repo: https://github.com/benlumia007/sandbox-custom-site.git
    hosts:
      - sandbox.test

  # example:
  #  repo: https://github.com/benlumia007/sandbox-custom-site.git
  #  hosts:
  #    - example.test

  # example:
  #  repo: https://github.com/benlumia007/sandbox-empty-site.git
  #  hosts:
  #    - example.test

# utilities
#
# Below is the extra resources that can be used to create additional neat features or software.
# Currently phpmyadmin and tls-ca ( SSL Certificates ) are the only one that's supported right
# now
utilities:
  core:
    - phpmyadmin
    - tls-ca

# vm_config
#
# vm_config controls how Vagrant works and you are enable to increase memory if you need more
# or if you wish to add more core to the virtual machine. Please take into consider that the
# memory and core have limitations on how much your hosts computer have.
vm_config:
  memory: 2048
  core: 2

# options
#
# Options are extra features that allows you to do backup of your database and restores them if
# both are set to true. Both Backup and Restores are set to true by default and it will do a
# backup when you do a vagrant halt and vagrant destroy. Restores happens if destroy the virtual
# machine, it will then restore all databases back to same user.  Xdebug is set to false since it
# takes more memory or whatnot, use it for your own sake but is not really config yet so that's
# something that you have to do on your own.
options:
  db_backups: true
  db_restores: true
  xdebug: false
